//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.29 at 10:10:19 PM KST 
//


package nurseryinfo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="generator" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="link" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="lastBuildDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="totalCount" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="pageCount" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="result" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="item">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="lat" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="subAddress" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="placeName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="newAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="lng" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="localName_2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="buildingAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="mountain" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="mainAddress" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="point_x" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="point_y" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="localName_1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="isNewAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="point_wx" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="point_wy" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="localName_3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "title",
    "description",
    "generator",
    "link",
    "lastBuildDate",
    "totalCount",
    "pageCount",
    "result",
    "item"
})
@XmlRootElement(name = "channel")
public class Channel {

    @XmlElement(required = true)
    protected String title;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(required = true)
    protected String generator;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String link;
    @XmlElement(required = true)
    protected String lastBuildDate;
    protected byte totalCount;
    protected byte pageCount;
    protected byte result;
    @XmlElement(required = true)
    protected Channel.Item item;

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the generator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenerator() {
        return generator;
    }

    /**
     * Sets the value of the generator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenerator(String value) {
        this.generator = value;
    }

    /**
     * Gets the value of the link property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLink() {
        return link;
    }

    /**
     * Sets the value of the link property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLink(String value) {
        this.link = value;
    }

    /**
     * Gets the value of the lastBuildDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastBuildDate() {
        return lastBuildDate;
    }

    /**
     * Sets the value of the lastBuildDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastBuildDate(String value) {
        this.lastBuildDate = value;
    }

    /**
     * Gets the value of the totalCount property.
     * 
     */
    public byte getTotalCount() {
        return totalCount;
    }

    /**
     * Sets the value of the totalCount property.
     * 
     */
    public void setTotalCount(byte value) {
        this.totalCount = value;
    }

    /**
     * Gets the value of the pageCount property.
     * 
     */
    public byte getPageCount() {
        return pageCount;
    }

    /**
     * Sets the value of the pageCount property.
     * 
     */
    public void setPageCount(byte value) {
        this.pageCount = value;
    }

    /**
     * Gets the value of the result property.
     * 
     */
    public byte getResult() {
        return result;
    }

    /**
     * Sets the value of the result property.
     * 
     */
    public void setResult(byte value) {
        this.result = value;
    }

    /**
     * Gets the value of the item property.
     * 
     * @return
     *     possible object is
     *     {@link Channel.Item }
     *     
     */
    public Channel.Item getItem() {
        return item;
    }

    /**
     * Sets the value of the item property.
     * 
     * @param value
     *     allowed object is
     *     {@link Channel.Item }
     *     
     */
    public void setItem(Channel.Item value) {
        this.item = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="lat" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="subAddress" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="placeName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="newAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="lng" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="localName_2" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="buildingAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="mountain" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="mainAddress" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="point_x" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="point_y" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="localName_1" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="isNewAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="point_wx" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="point_wy" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="localName_3" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "lat",
        "id",
        "subAddress",
        "placeName",
        "newAddress",
        "lng",
        "localName2",
        "buildingAddress",
        "mountain",
        "mainAddress",
        "pointX",
        "pointY",
        "localName1",
        "title",
        "isNewAddress",
        "pointWx",
        "pointWy",
        "localName3"
    })
    public static class Item {

        protected String lat;
        @XmlElement(required = true)
        protected String id;
        protected byte subAddress;
        @XmlElement(required = true)
        protected String placeName;
        @XmlElement(required = true)
        protected String newAddress;
        protected String lng;
        @XmlElement(name = "localName_2", required = true)
        protected String localName2;
        @XmlElement(required = true)
        protected String buildingAddress;
        @XmlElement(required = true)
        protected String mountain;
        protected byte mainAddress;
        @XmlElement(name = "point_x")
        protected float pointX;
        @XmlElement(name = "point_y")
        protected float pointY;
        @XmlElement(name = "localName_1", required = true)
        protected String localName1;
        @XmlElement(required = true)
        protected String title;
        @XmlElement(required = true)
        protected String isNewAddress;
        @XmlElement(name = "point_wx")
        protected int pointWx;
        @XmlElement(name = "point_wy")
        protected int pointWy;
        @XmlElement(name = "localName_3", required = true)
        protected String localName3;

        /**
         * Gets the value of the lat property.
         * 
         */
        public String getLat() {
            return lat;
        }

        /**
         * Sets the value of the lat property.
         * 
         */
        public void setLat(String value) {
            this.lat = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the subAddress property.
         * 
         */
        public byte getSubAddress() {
            return subAddress;
        }

        /**
         * Sets the value of the subAddress property.
         * 
         */
        public void setSubAddress(byte value) {
            this.subAddress = value;
        }

        /**
         * Gets the value of the placeName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlaceName() {
            return placeName;
        }

        /**
         * Sets the value of the placeName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlaceName(String value) {
            this.placeName = value;
        }

        /**
         * Gets the value of the newAddress property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNewAddress() {
            return newAddress;
        }

        /**
         * Sets the value of the newAddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNewAddress(String value) {
            this.newAddress = value;
        }

        /**
         * Gets the value of the lng property.
         * 
         */
        public String getLng() {
            return lng;
        }

        /**
         * Sets the value of the lng property.
         * 
         */
        public void setLng(String value) {
            this.lng = value;
        }

        /**
         * Gets the value of the localName2 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLocalName2() {
            return localName2;
        }

        /**
         * Sets the value of the localName2 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLocalName2(String value) {
            this.localName2 = value;
        }

        /**
         * Gets the value of the buildingAddress property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBuildingAddress() {
            return buildingAddress;
        }

        /**
         * Sets the value of the buildingAddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBuildingAddress(String value) {
            this.buildingAddress = value;
        }

        /**
         * Gets the value of the mountain property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMountain() {
            return mountain;
        }

        /**
         * Sets the value of the mountain property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMountain(String value) {
            this.mountain = value;
        }

        /**
         * Gets the value of the mainAddress property.
         * 
         */
        public byte getMainAddress() {
            return mainAddress;
        }

        /**
         * Sets the value of the mainAddress property.
         * 
         */
        public void setMainAddress(byte value) {
            this.mainAddress = value;
        }

        /**
         * Gets the value of the pointX property.
         * 
         */
        public float getPointX() {
            return pointX;
        }

        /**
         * Sets the value of the pointX property.
         * 
         */
        public void setPointX(float value) {
            this.pointX = value;
        }

        /**
         * Gets the value of the pointY property.
         * 
         */
        public float getPointY() {
            return pointY;
        }

        /**
         * Sets the value of the pointY property.
         * 
         */
        public void setPointY(float value) {
            this.pointY = value;
        }

        /**
         * Gets the value of the localName1 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLocalName1() {
            return localName1;
        }

        /**
         * Sets the value of the localName1 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLocalName1(String value) {
            this.localName1 = value;
        }

        /**
         * Gets the value of the title property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTitle() {
            return title;
        }

        /**
         * Sets the value of the title property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTitle(String value) {
            this.title = value;
        }

        /**
         * Gets the value of the isNewAddress property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIsNewAddress() {
            return isNewAddress;
        }

        /**
         * Sets the value of the isNewAddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIsNewAddress(String value) {
            this.isNewAddress = value;
        }

        /**
         * Gets the value of the pointWx property.
         * 
         */
        public int getPointWx() {
            return pointWx;
        }

        /**
         * Sets the value of the pointWx property.
         * 
         */
        public void setPointWx(int value) {
            this.pointWx = value;
        }

        /**
         * Gets the value of the pointWy property.
         * 
         */
        public int getPointWy() {
            return pointWy;
        }

        /**
         * Sets the value of the pointWy property.
         * 
         */
        public void setPointWy(int value) {
            this.pointWy = value;
        }

        /**
         * Gets the value of the localName3 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLocalName3() {
            return localName3;
        }

        /**
         * Sets the value of the localName3 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLocalName3(String value) {
            this.localName3 = value;
        }

    }

}
