//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.17 at 01:18:21 PM KST 
//


package nurseryinfo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="item" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="stcode" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="crname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="crtel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="crfax" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="craddr" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="crhome" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="crcapat" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "item"
})
@XmlRootElement(name = "response")
public class NurseryInfo {

    protected List<NurseryInfo.Item> item;

    /**
     * Gets the value of the item property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the item property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NurseryInfo.Item }
     * 
     * 
     */
    public List<NurseryInfo.Item> getItem() {
        if (item == null) {
            item = new ArrayList<NurseryInfo.Item>();
        }
        return this.item;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="stcode" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *         &lt;element name="crname" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="crtel" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="crfax" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="craddr" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="crhome" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="crcapat" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "stcode",
        "crname",
        "crtel",
        "crfax",
        "craddr",
        "crhome",
        "crcapat"
    })
    public static class Item {

        protected long stcode;
        @XmlElement(required = true)
        protected String crname;
        @XmlElement(required = true)
        protected String crtel;
        @XmlElement(required = true)
        protected String crfax;
        @XmlElement(required = true)
        protected String craddr;
        @XmlElement(required = true)
        protected String crhome;
        protected short crcapat;

        /**
         * Gets the value of the stcode property.
         * 
         */
        public long getStcode() {
            return stcode;
        }

        /**
         * Sets the value of the stcode property.
         * 
         */
        public void setStcode(long value) {
            this.stcode = value;
        }

        /**
         * Gets the value of the crname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCrname() {
            return crname;
        }

        /**
         * Sets the value of the crname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCrname(String value) {
            this.crname = value;
        }

        /**
         * Gets the value of the crtel property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCrtel() {
            return crtel;
        }

        /**
         * Sets the value of the crtel property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCrtel(String value) {
            this.crtel = value;
        }

        /**
         * Gets the value of the crfax property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCrfax() {
            return crfax;
        }

        /**
         * Sets the value of the crfax property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCrfax(String value) {
            this.crfax = value;
        }

        /**
         * Gets the value of the craddr property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCraddr() {
            return craddr;
        }

        /**
         * Sets the value of the craddr property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCraddr(String value) {
            this.craddr = value;
        }

        /**
         * Gets the value of the crhome property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCrhome() {
            return crhome;
        }

        /**
         * Sets the value of the crhome property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCrhome(String value) {
            this.crhome = value;
        }

        /**
         * Gets the value of the crcapat property.
         * 
         */
        public short getCrcapat() {
            return crcapat;
        }

        /**
         * Sets the value of the crcapat property.
         * 
         */
        public void setCrcapat(short value) {
            this.crcapat = value;
        }

    }

}
